local item={	
	ID="1"	ItemId="14"	Desc=""	BigIconName="zuan2"	ItemName="4618"	ItemType="0"	IsCanUse="0"	IsCanSend="1"	IsCanBuy="0"	MaxPileCount="0"	MinSendCount="1"	MaxSendCount="999"	IsShowInBag="0"	BagIconName="zuan2"	MailIconName="zuan2"	ShowPosition=""	TorpedoIcon=""	GiftIcon="zuan2"	
	ID="2"	ItemId="21"	Desc="4624"	BigIconName="Super-img-chaonengpao"	ItemName="4655"	ItemType="0"	IsCanUse="0"	IsCanSend="1"	IsCanBuy="0"	MaxPileCount="0"	MinSendCount="1"	MaxSendCount="999"	IsShowInBag="0"	BagIconName="Super-img-chaonengpao"	MailIconName="bz_chaonengpao"	ShowPosition=""	TorpedoIcon=""	GiftIcon="Super-img-chaonengpao"	
	ID="3"	ItemId="22"	Desc="4625"	BigIconName="Super-img-zuantoupao"	ItemName="4656"	ItemType="0"	IsCanUse="0"	IsCanSend="1"	IsCanBuy="0"	MaxPileCount="0"	MinSendCount="1"	MaxSendCount="999"	IsShowInBag="0"	BagIconName="Super-img-zuantoupao"	MailIconName="bz_zuantoupao"	ShowPosition=""	TorpedoIcon=""	GiftIcon="Super-img-zuantoupao"	
	ID="4"	ItemId="4"	Desc=""	BigIconName="diamond"	ItemName="4616"	ItemType="0"	IsCanUse="0"	IsCanSend="1"	IsCanBuy="0"	MaxPileCount="0"	MinSendCount="1"	MaxSendCount="999"	IsShowInBag="0"	BagIconName="diamond"	MailIconName="diamond"	ShowPosition=""	TorpedoIcon=""	GiftIcon="icon10"	
	ID="5"	ItemId="5"	Desc=""	BigIconName="bank-img-jinbi"	ItemName="4614"	ItemType="0"	IsCanUse="0"	IsCanSend="1"	IsCanBuy="0"	MaxPileCount="0"	MinSendCount="1"	MaxSendCount="999"	IsShowInBag="0"	BagIconName="bank-img-jinbi"	MailIconName="bank-img-jinbi"	ShowPosition=""	TorpedoIcon=""	GiftIcon="icon02"	
	ID="6"	ItemId="41"	Desc="4627"	BigIconName="putongyulei_03"	ItemName="4626"	ItemType="0"	IsCanUse="0"	IsCanSend="1"	IsCanBuy="0"	MaxPileCount="0"	MinSendCount="10"	MaxSendCount="999"	IsShowInBag="1"	BagIconName="putongyulei_03"	MailIconName="putongyulei_03"	ShowPosition="bag"	TorpedoIcon="torpedo-img-putongyulei2"	GiftIcon="putongyulei_03"	
	ID="7"	ItemId="42"	Desc="4629"	BigIconName="baiyinyulei_03"	ItemName="4628"	ItemType="0"	IsCanUse="0"	IsCanSend="1"	IsCanBuy="0"	MaxPileCount="0"	MinSendCount="1"	MaxSendCount="999"	IsShowInBag="1"	BagIconName="baiyinyulei_03"	MailIconName="baiyinyulei_03"	ShowPosition="bag"	TorpedoIcon="torpedo-img-baiyinyulei2"	GiftIcon="baiyinyulei_03"	
	ID="8"	ItemId="43"	Desc="4631"	BigIconName="huangjinyulei_03"	ItemName="4630"	ItemType="0"	IsCanUse="0"	IsCanSend="1"	IsCanBuy="0"	MaxPileCount="0"	MinSendCount="1"	MaxSendCount="999"	IsShowInBag="1"	BagIconName="huangjinyulei_03"	MailIconName="huangjinyulei_03"	ShowPosition="bag"	TorpedoIcon="torpedo-img-huangjinyulei2"	GiftIcon="huangjinyulei_03"	
	ID="9"	ItemId="44"	Desc="4633"	BigIconName="zijinyulei_03"	ItemName="4632"	ItemType="0"	IsCanUse="0"	IsCanSend="1"	IsCanBuy="0"	MaxPileCount="0"	MinSendCount="1"	MaxSendCount="999"	IsShowInBag="1"	BagIconName="zijinyulei_03"	MailIconName="zijinyulei_03"	ShowPosition="bag"	TorpedoIcon="torpedo-img-zijinyule2"	GiftIcon="zijinyulei_03"	
	ID="10"	ItemId="45"	Desc="4635"	BigIconName="qicaiyulei_03"	ItemName="4634"	ItemType="0"	IsCanUse="0"	IsCanSend="1"	IsCanBuy="0"	MaxPileCount="0"	MinSendCount="1"	MaxSendCount="999"	IsShowInBag="1"	BagIconName="qicaiyulei_03"	MailIconName="qicaiyulei_03"	ShowPosition="bag"	TorpedoIcon="torpedo-img-qicaiyulei2"	GiftIcon="qicaiyulei_03"	
	ID="11"	ItemId="1"	Desc=""	BigIconName=""	ItemName=""	ItemType="0"	IsCanUse="0"	IsCanSend="1"	IsCanBuy="0"	MaxPileCount="0"	MinSendCount="1"	MaxSendCount="999"	IsShowInBag="0"	BagIconName=""	MailIconName=""	ShowPosition=""	TorpedoIcon=""	GiftIcon="Battery-img-jinengtubiao5_03"	
	ID="12"	ItemId="-1"	Desc=""	BigIconName=""	ItemName=""	ItemType="0"	IsCanUse="0"	IsCanSend="1"	IsCanBuy="0"	MaxPileCount="0"	MinSendCount="1"	MaxSendCount="999"	IsShowInBag="0"	BagIconName=""	MailIconName=""	ShowPosition=""	TorpedoIcon=""	GiftIcon=""	
	ID="15"	ItemId="0"	Desc=""	BigIconName=""	ItemName=""	ItemType="0"	IsCanUse="0"	IsCanSend="1"	IsCanBuy="0"	MaxPileCount="0"	MinSendCount="1"	MaxSendCount="999"	IsShowInBag="0"	BagIconName=""	MailIconName=""	ShowPosition=""	TorpedoIcon=""	GiftIcon=""	
	ID="16"	ItemId="2"	Desc=""	BigIconName=""	ItemName=""	ItemType="0"	IsCanUse="0"	IsCanSend="1"	IsCanBuy="0"	MaxPileCount="0"	MinSendCount="1"	MaxSendCount="999"	IsShowInBag="0"	BagIconName=""	MailIconName=""	ShowPosition=""	TorpedoIcon=""	GiftIcon=""	
	ID="17"	ItemId="3"	Desc=""	BigIconName=""	ItemName=""	ItemType="0"	IsCanUse="0"	IsCanSend="1"	IsCanBuy="0"	MaxPileCount="0"	MinSendCount="1"	MaxSendCount="999"	IsShowInBag="0"	BagIconName=""	MailIconName=""	ShowPosition=""	TorpedoIcon=""	GiftIcon=""	
}
 return item