// Code generated by protoc-gen-go. DO NOT EDIT.
// source: LandlordsProto.proto

/*
Package msg is a generated protocol buffer package.

It is generated from these files:
	LandlordsProto.proto

It has these top-level messages:
	CS_PlayerLogin
	SC_PlayerLogin
	CS_PlayerRegister
	SC_PlayerRegister
	CS_Heartbeat
	SC_Heartbeat
*/
package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SC_PlayerLogin_LoginResult int32

const (
	SC_PlayerLogin_SUCCESS       SC_PlayerLogin_LoginResult = 0
	SC_PlayerLogin_ACCOUNT_ERROR SC_PlayerLogin_LoginResult = 1
	SC_PlayerLogin_PWD_ERROR     SC_PlayerLogin_LoginResult = 2
)

var SC_PlayerLogin_LoginResult_name = map[int32]string{
	0: "SUCCESS",
	1: "ACCOUNT_ERROR",
	2: "PWD_ERROR",
}
var SC_PlayerLogin_LoginResult_value = map[string]int32{
	"SUCCESS":       0,
	"ACCOUNT_ERROR": 1,
	"PWD_ERROR":     2,
}

func (x SC_PlayerLogin_LoginResult) String() string {
	return proto.EnumName(SC_PlayerLogin_LoginResult_name, int32(x))
}
func (SC_PlayerLogin_LoginResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

type SC_PlayerRegister_RegisterResult int32

const (
	SC_PlayerRegister_SUCCESS       SC_PlayerRegister_RegisterResult = 0
	SC_PlayerRegister_ACCOUNT_ERROR SC_PlayerRegister_RegisterResult = 1
)

var SC_PlayerRegister_RegisterResult_name = map[int32]string{
	0: "SUCCESS",
	1: "ACCOUNT_ERROR",
}
var SC_PlayerRegister_RegisterResult_value = map[string]int32{
	"SUCCESS":       0,
	"ACCOUNT_ERROR": 1,
}

func (x SC_PlayerRegister_RegisterResult) String() string {
	return proto.EnumName(SC_PlayerRegister_RegisterResult_name, int32(x))
}
func (SC_PlayerRegister_RegisterResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3, 0}
}

type CS_PlayerLogin struct {
	Account string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Pwd     string `protobuf:"bytes,2,opt,name=pwd" json:"pwd,omitempty"`
}

func (m *CS_PlayerLogin) Reset()                    { *m = CS_PlayerLogin{} }
func (m *CS_PlayerLogin) String() string            { return proto.CompactTextString(m) }
func (*CS_PlayerLogin) ProtoMessage()               {}
func (*CS_PlayerLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CS_PlayerLogin) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CS_PlayerLogin) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type SC_PlayerLogin struct {
	LoginResult SC_PlayerLogin_LoginResult `protobuf:"varint,1,opt,name=loginResult,enum=msg.SC_PlayerLogin_LoginResult" json:"loginResult,omitempty"`
}

func (m *SC_PlayerLogin) Reset()                    { *m = SC_PlayerLogin{} }
func (m *SC_PlayerLogin) String() string            { return proto.CompactTextString(m) }
func (*SC_PlayerLogin) ProtoMessage()               {}
func (*SC_PlayerLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SC_PlayerLogin) GetLoginResult() SC_PlayerLogin_LoginResult {
	if m != nil {
		return m.LoginResult
	}
	return SC_PlayerLogin_SUCCESS
}

type CS_PlayerRegister struct {
	Account string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Pwd     string `protobuf:"bytes,2,opt,name=pwd" json:"pwd,omitempty"`
}

func (m *CS_PlayerRegister) Reset()                    { *m = CS_PlayerRegister{} }
func (m *CS_PlayerRegister) String() string            { return proto.CompactTextString(m) }
func (*CS_PlayerRegister) ProtoMessage()               {}
func (*CS_PlayerRegister) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CS_PlayerRegister) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CS_PlayerRegister) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type SC_PlayerRegister struct {
	RegisterResult SC_PlayerRegister_RegisterResult `protobuf:"varint,1,opt,name=registerResult,enum=msg.SC_PlayerRegister_RegisterResult" json:"registerResult,omitempty"`
}

func (m *SC_PlayerRegister) Reset()                    { *m = SC_PlayerRegister{} }
func (m *SC_PlayerRegister) String() string            { return proto.CompactTextString(m) }
func (*SC_PlayerRegister) ProtoMessage()               {}
func (*SC_PlayerRegister) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SC_PlayerRegister) GetRegisterResult() SC_PlayerRegister_RegisterResult {
	if m != nil {
		return m.RegisterResult
	}
	return SC_PlayerRegister_SUCCESS
}

type CS_Heartbeat struct {
}

func (m *CS_Heartbeat) Reset()                    { *m = CS_Heartbeat{} }
func (m *CS_Heartbeat) String() string            { return proto.CompactTextString(m) }
func (*CS_Heartbeat) ProtoMessage()               {}
func (*CS_Heartbeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type SC_Heartbeat struct {
	ServerTime int64 `protobuf:"zigzag64,1,opt,name=serverTime" json:"serverTime,omitempty"`
}

func (m *SC_Heartbeat) Reset()                    { *m = SC_Heartbeat{} }
func (m *SC_Heartbeat) String() string            { return proto.CompactTextString(m) }
func (*SC_Heartbeat) ProtoMessage()               {}
func (*SC_Heartbeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SC_Heartbeat) GetServerTime() int64 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

func init() {
	proto.RegisterType((*CS_PlayerLogin)(nil), "msg.CS_PlayerLogin")
	proto.RegisterType((*SC_PlayerLogin)(nil), "msg.SC_PlayerLogin")
	proto.RegisterType((*CS_PlayerRegister)(nil), "msg.CS_PlayerRegister")
	proto.RegisterType((*SC_PlayerRegister)(nil), "msg.SC_PlayerRegister")
	proto.RegisterType((*CS_Heartbeat)(nil), "msg.CS_Heartbeat")
	proto.RegisterType((*SC_Heartbeat)(nil), "msg.SC_Heartbeat")
	proto.RegisterEnum("msg.SC_PlayerLogin_LoginResult", SC_PlayerLogin_LoginResult_name, SC_PlayerLogin_LoginResult_value)
	proto.RegisterEnum("msg.SC_PlayerRegister_RegisterResult", SC_PlayerRegister_RegisterResult_name, SC_PlayerRegister_RegisterResult_value)
}

func init() { proto.RegisterFile("LandlordsProto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0xbf, 0xb4, 0xf0, 0x95, 0xde, 0xb4, 0x43, 0x32, 0xb8, 0xc8, 0x4a, 0x65, 0x40, 0x70,
	0x35, 0x88, 0x6e, 0x0b, 0x52, 0xc6, 0x82, 0x8b, 0x68, 0xc3, 0x4c, 0x8b, 0xcb, 0x90, 0x36, 0x43,
	0x08, 0xe4, 0x4f, 0x99, 0x99, 0x2a, 0x3e, 0x86, 0xe0, 0x03, 0x4b, 0x62, 0x9b, 0x66, 0xdc, 0x88,
	0x9b, 0x70, 0xce, 0xcd, 0x39, 0x97, 0xfb, 0x63, 0xe0, 0x2c, 0x4c, 0xaa, 0xb4, 0xa8, 0x55, 0xaa,
	0x23, 0x55, 0x9b, 0x9a, 0xee, 0x9a, 0x2f, 0x1e, 0x96, 0x3a, 0x23, 0x33, 0x40, 0x4c, 0xc4, 0x51,
	0x91, 0xbc, 0x4b, 0x15, 0xd6, 0x59, 0x5e, 0xe1, 0x00, 0x46, 0xc9, 0x76, 0x5b, 0xef, 0x2b, 0x13,
	0x38, 0x97, 0xce, 0xf5, 0x98, 0x1f, 0x2d, 0xf6, 0x60, 0xb8, 0x7b, 0x4b, 0x83, 0x41, 0x3b, 0x6d,
	0x24, 0xf9, 0x70, 0x00, 0x09, 0x66, 0xd5, 0xe7, 0xe0, 0x16, 0x8d, 0xe0, 0x52, 0xef, 0x8b, 0xef,
	0x15, 0xe8, 0xf6, 0x82, 0x96, 0x3a, 0xa3, 0x76, 0x92, 0x86, 0xa7, 0x18, 0xef, 0x77, 0xc8, 0x0c,
	0xdc, 0xde, 0x3f, 0xec, 0xc2, 0x48, 0xac, 0x19, 0x5b, 0x08, 0xe1, 0xfd, 0xc3, 0x3e, 0x4c, 0xe7,
	0x8c, 0x2d, 0xd7, 0xcf, 0xab, 0x78, 0xc1, 0xf9, 0x92, 0x7b, 0x0e, 0x9e, 0xc2, 0x38, 0x7a, 0x79,
	0x38, 0xd8, 0x01, 0xb9, 0x07, 0xbf, 0x23, 0xe2, 0x32, 0xcb, 0xb5, 0x91, 0xea, 0x4f, 0x50, 0x9f,
	0x0e, 0xf8, 0xdd, 0xa9, 0xdd, 0x86, 0x27, 0x40, 0xea, 0xa0, 0x2d, 0xb4, 0x2b, 0x1b, 0xed, 0x98,
	0xa7, 0xdc, 0x0a, 0xf3, 0x1f, 0x65, 0x72, 0x03, 0xc8, 0x4e, 0xfc, 0x86, 0x49, 0x10, 0x4c, 0x98,
	0x88, 0x1f, 0x65, 0xa2, 0xcc, 0x46, 0x26, 0x86, 0x50, 0x98, 0x08, 0x76, 0xf2, 0xf8, 0x1c, 0x40,
	0x4b, 0xf5, 0x2a, 0xd5, 0x2a, 0x2f, 0x65, 0x7b, 0x1c, 0xe6, 0xbd, 0xc9, 0xe6, 0x7f, 0xfb, 0xea,
	0x77, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x43, 0xcd, 0x20, 0x75, 0x0d, 0x02, 0x00, 0x00,
}
