// Code generated by protoc-gen-go. DO NOT EDIT.
// source: LandlordsProto.proto

/*
Package msg is a generated protocol buffer package.

It is generated from these files:
	LandlordsProto.proto

It has these top-level messages:
	CS_PlayerLogin
	SC_PlayerLogin
	CS_PlayerRegister
	SC_PlayerRegister
	PlayerInfo
	CS_PlayerInfo
	SC_PlayerInfo
	CS_Heartbeat
	SC_Heartbeat
	CS_PlayerReady
	SC_PlayerReady
	CS_PlayerCancelReady
	SC_PlayerCancelReady
	SC_PlayerCard
	CS_PlayerGrabHost
	SC_PlayerGrabHost
	CS_PutCard
	SC_PutCard
	SC_GameResult
*/
package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CS_PlayerLogin struct {
	Account          *string `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	Pwd              *string `protobuf:"bytes,2,req,name=pwd" json:"pwd,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CS_PlayerLogin) Reset()                    { *m = CS_PlayerLogin{} }
func (m *CS_PlayerLogin) String() string            { return proto.CompactTextString(m) }
func (*CS_PlayerLogin) ProtoMessage()               {}
func (*CS_PlayerLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CS_PlayerLogin) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *CS_PlayerLogin) GetPwd() string {
	if m != nil && m.Pwd != nil {
		return *m.Pwd
	}
	return ""
}

type SC_PlayerLogin struct {
	// 0成功 1账号错误 2密码错误
	Result           *int32  `protobuf:"zigzag32,1,req,name=result" json:"result,omitempty"`
	PlayerId         *uint64 `protobuf:"varint,2,req,name=playerId" json:"playerId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SC_PlayerLogin) Reset()                    { *m = SC_PlayerLogin{} }
func (m *SC_PlayerLogin) String() string            { return proto.CompactTextString(m) }
func (*SC_PlayerLogin) ProtoMessage()               {}
func (*SC_PlayerLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SC_PlayerLogin) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *SC_PlayerLogin) GetPlayerId() uint64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

type CS_PlayerRegister struct {
	Account          *string `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	Pwd              *string `protobuf:"bytes,2,req,name=pwd" json:"pwd,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CS_PlayerRegister) Reset()                    { *m = CS_PlayerRegister{} }
func (m *CS_PlayerRegister) String() string            { return proto.CompactTextString(m) }
func (*CS_PlayerRegister) ProtoMessage()               {}
func (*CS_PlayerRegister) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CS_PlayerRegister) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *CS_PlayerRegister) GetPwd() string {
	if m != nil && m.Pwd != nil {
		return *m.Pwd
	}
	return ""
}

type SC_PlayerRegister struct {
	// 0成功 1账号错误
	Result           *int32 `protobuf:"zigzag32,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SC_PlayerRegister) Reset()                    { *m = SC_PlayerRegister{} }
func (m *SC_PlayerRegister) String() string            { return proto.CompactTextString(m) }
func (*SC_PlayerRegister) ProtoMessage()               {}
func (*SC_PlayerRegister) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SC_PlayerRegister) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

type PlayerInfo struct {
	PlayerId         *uint64 `protobuf:"varint,1,req,name=playerId" json:"playerId,omitempty"`
	PlayerAccount    *string `protobuf:"bytes,2,req,name=playerAccount" json:"playerAccount,omitempty"`
	PlayerName       *string `protobuf:"bytes,3,opt,name=playerName" json:"playerName,omitempty"`
	PlayerCoin       *uint64 `protobuf:"varint,4,opt,name=playerCoin" json:"playerCoin,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerInfo) Reset()                    { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string            { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()               {}
func (*PlayerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PlayerInfo) GetPlayerId() uint64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *PlayerInfo) GetPlayerAccount() string {
	if m != nil && m.PlayerAccount != nil {
		return *m.PlayerAccount
	}
	return ""
}

func (m *PlayerInfo) GetPlayerName() string {
	if m != nil && m.PlayerName != nil {
		return *m.PlayerName
	}
	return ""
}

func (m *PlayerInfo) GetPlayerCoin() uint64 {
	if m != nil && m.PlayerCoin != nil {
		return *m.PlayerCoin
	}
	return 0
}

type CS_PlayerInfo struct {
	PlayerId         *int32 `protobuf:"zigzag32,1,req,name=playerId" json:"playerId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CS_PlayerInfo) Reset()                    { *m = CS_PlayerInfo{} }
func (m *CS_PlayerInfo) String() string            { return proto.CompactTextString(m) }
func (*CS_PlayerInfo) ProtoMessage()               {}
func (*CS_PlayerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CS_PlayerInfo) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

type SC_PlayerInfo struct {
	PlayerInfo *PlayerInfo `protobuf:"bytes,1,req,name=playerInfo" json:"playerInfo,omitempty"`
	// -1:用户不存在 0:用户存在
	Result           *int32 `protobuf:"zigzag32,2,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SC_PlayerInfo) Reset()                    { *m = SC_PlayerInfo{} }
func (m *SC_PlayerInfo) String() string            { return proto.CompactTextString(m) }
func (*SC_PlayerInfo) ProtoMessage()               {}
func (*SC_PlayerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SC_PlayerInfo) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

func (m *SC_PlayerInfo) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

type CS_Heartbeat struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CS_Heartbeat) Reset()                    { *m = CS_Heartbeat{} }
func (m *CS_Heartbeat) String() string            { return proto.CompactTextString(m) }
func (*CS_Heartbeat) ProtoMessage()               {}
func (*CS_Heartbeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type SC_Heartbeat struct {
	ServerTime       *int64 `protobuf:"zigzag64,1,req,name=serverTime" json:"serverTime,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SC_Heartbeat) Reset()                    { *m = SC_Heartbeat{} }
func (m *SC_Heartbeat) String() string            { return proto.CompactTextString(m) }
func (*SC_Heartbeat) ProtoMessage()               {}
func (*SC_Heartbeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *SC_Heartbeat) GetServerTime() int64 {
	if m != nil && m.ServerTime != nil {
		return *m.ServerTime
	}
	return 0
}

// 用户准备
type CS_PlayerReady struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CS_PlayerReady) Reset()                    { *m = CS_PlayerReady{} }
func (m *CS_PlayerReady) String() string            { return proto.CompactTextString(m) }
func (*CS_PlayerReady) ProtoMessage()               {}
func (*CS_PlayerReady) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type SC_PlayerReady struct {
	Result           *int32 `protobuf:"zigzag32,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SC_PlayerReady) Reset()                    { *m = SC_PlayerReady{} }
func (m *SC_PlayerReady) String() string            { return proto.CompactTextString(m) }
func (*SC_PlayerReady) ProtoMessage()               {}
func (*SC_PlayerReady) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *SC_PlayerReady) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// 用户取消准备
type CS_PlayerCancelReady struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CS_PlayerCancelReady) Reset()                    { *m = CS_PlayerCancelReady{} }
func (m *CS_PlayerCancelReady) String() string            { return proto.CompactTextString(m) }
func (*CS_PlayerCancelReady) ProtoMessage()               {}
func (*CS_PlayerCancelReady) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type SC_PlayerCancelReady struct {
	// 0:成功 -1:失败
	Result           *int32 `protobuf:"zigzag32,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SC_PlayerCancelReady) Reset()                    { *m = SC_PlayerCancelReady{} }
func (m *SC_PlayerCancelReady) String() string            { return proto.CompactTextString(m) }
func (*SC_PlayerCancelReady) ProtoMessage()               {}
func (*SC_PlayerCancelReady) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *SC_PlayerCancelReady) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// 下发卡牌信息
type SC_PlayerCard struct {
	// cardId/4==卡牌值(0:A 1:1 ------>11:Q 12:K,52小王 53大王)
	// cardId%4==卡牌类型(0:红 1:方 2:黑 3:梅)
	CardId   []int32 `protobuf:"zigzag32,1,rep,name=cardId" json:"cardId,omitempty"`
	PlayerId *uint64 `protobuf:"varint,2,req,name=playerId" json:"playerId,omitempty"`
	// 玩家位置，玩家处于1位置，左侧为0，右侧为2
	Position *int32 `protobuf:"zigzag32,3,req,name=position" json:"position,omitempty"`
	// 地主底牌
	Cards            *int32 `protobuf:"zigzag32,4,req,name=cards" json:"cards,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SC_PlayerCard) Reset()                    { *m = SC_PlayerCard{} }
func (m *SC_PlayerCard) String() string            { return proto.CompactTextString(m) }
func (*SC_PlayerCard) ProtoMessage()               {}
func (*SC_PlayerCard) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *SC_PlayerCard) GetCardId() []int32 {
	if m != nil {
		return m.CardId
	}
	return nil
}

func (m *SC_PlayerCard) GetPlayerId() uint64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *SC_PlayerCard) GetPosition() int32 {
	if m != nil && m.Position != nil {
		return *m.Position
	}
	return 0
}

func (m *SC_PlayerCard) GetCards() int32 {
	if m != nil && m.Cards != nil {
		return *m.Cards
	}
	return 0
}

// 玩家抢地主
type CS_PlayerGrabHost struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CS_PlayerGrabHost) Reset()                    { *m = CS_PlayerGrabHost{} }
func (m *CS_PlayerGrabHost) String() string            { return proto.CompactTextString(m) }
func (*CS_PlayerGrabHost) ProtoMessage()               {}
func (*CS_PlayerGrabHost) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type SC_PlayerGrabHost struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SC_PlayerGrabHost) Reset()                    { *m = SC_PlayerGrabHost{} }
func (m *SC_PlayerGrabHost) String() string            { return proto.CompactTextString(m) }
func (*SC_PlayerGrabHost) ProtoMessage()               {}
func (*SC_PlayerGrabHost) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type CS_PutCard struct {
	CardId           []int32 `protobuf:"zigzag32,1,rep,name=cardId" json:"cardId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CS_PutCard) Reset()                    { *m = CS_PutCard{} }
func (m *CS_PutCard) String() string            { return proto.CompactTextString(m) }
func (*CS_PutCard) ProtoMessage()               {}
func (*CS_PutCard) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *CS_PutCard) GetCardId() []int32 {
	if m != nil {
		return m.CardId
	}
	return nil
}

type SC_PutCard struct {
	Result           *int32 `protobuf:"zigzag32,1,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SC_PutCard) Reset()                    { *m = SC_PutCard{} }
func (m *SC_PutCard) String() string            { return proto.CompactTextString(m) }
func (*SC_PutCard) ProtoMessage()               {}
func (*SC_PutCard) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *SC_PutCard) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

type SC_GameResult struct {
	// 0：地主获胜 1：农民获胜
	GameWinType      *int32 `protobuf:"zigzag32,1,req,name=gameWinType" json:"gameWinType,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SC_GameResult) Reset()                    { *m = SC_GameResult{} }
func (m *SC_GameResult) String() string            { return proto.CompactTextString(m) }
func (*SC_GameResult) ProtoMessage()               {}
func (*SC_GameResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *SC_GameResult) GetGameWinType() int32 {
	if m != nil && m.GameWinType != nil {
		return *m.GameWinType
	}
	return 0
}

func init() {
	proto.RegisterType((*CS_PlayerLogin)(nil), "msg.CS_PlayerLogin")
	proto.RegisterType((*SC_PlayerLogin)(nil), "msg.SC_PlayerLogin")
	proto.RegisterType((*CS_PlayerRegister)(nil), "msg.CS_PlayerRegister")
	proto.RegisterType((*SC_PlayerRegister)(nil), "msg.SC_PlayerRegister")
	proto.RegisterType((*PlayerInfo)(nil), "msg.PlayerInfo")
	proto.RegisterType((*CS_PlayerInfo)(nil), "msg.CS_PlayerInfo")
	proto.RegisterType((*SC_PlayerInfo)(nil), "msg.SC_PlayerInfo")
	proto.RegisterType((*CS_Heartbeat)(nil), "msg.CS_Heartbeat")
	proto.RegisterType((*SC_Heartbeat)(nil), "msg.SC_Heartbeat")
	proto.RegisterType((*CS_PlayerReady)(nil), "msg.CS_PlayerReady")
	proto.RegisterType((*SC_PlayerReady)(nil), "msg.SC_PlayerReady")
	proto.RegisterType((*CS_PlayerCancelReady)(nil), "msg.CS_PlayerCancelReady")
	proto.RegisterType((*SC_PlayerCancelReady)(nil), "msg.SC_PlayerCancelReady")
	proto.RegisterType((*SC_PlayerCard)(nil), "msg.SC_PlayerCard")
	proto.RegisterType((*CS_PlayerGrabHost)(nil), "msg.CS_PlayerGrabHost")
	proto.RegisterType((*SC_PlayerGrabHost)(nil), "msg.SC_PlayerGrabHost")
	proto.RegisterType((*CS_PutCard)(nil), "msg.CS_PutCard")
	proto.RegisterType((*SC_PutCard)(nil), "msg.SC_PutCard")
	proto.RegisterType((*SC_GameResult)(nil), "msg.SC_GameResult")
}

func init() { proto.RegisterFile("LandlordsProto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x5d, 0x6b, 0xdb, 0x30,
	0x14, 0xc5, 0x71, 0xf6, 0xd1, 0xdb, 0x26, 0x6b, 0xb4, 0x50, 0xcc, 0x1e, 0x46, 0x10, 0x7d, 0x30,
	0x14, 0x3c, 0xb6, 0xe7, 0xc1, 0x18, 0x1e, 0xb4, 0x85, 0x32, 0x8a, 0x5c, 0xd8, 0xde, 0x8a, 0x6a,
	0x6b, 0xc6, 0x60, 0x4b, 0x46, 0x92, 0x37, 0xf2, 0x27, 0xf6, 0x9b, 0x87, 0x24, 0x57, 0x96, 0x61,
	0x29, 0xf4, 0x25, 0xe8, 0x1c, 0x9d, 0x7b, 0x75, 0xee, 0xc9, 0x35, 0x6c, 0x6f, 0x28, 0xaf, 0x5a,
	0x21, 0x2b, 0x75, 0x2b, 0x85, 0x16, 0x59, 0x6f, 0x7e, 0x51, 0xdc, 0xa9, 0x1a, 0x7f, 0x86, 0x75,
	0x5e, 0xdc, 0xdf, 0xb6, 0x74, 0xcf, 0xe4, 0x8d, 0xa8, 0x1b, 0x8e, 0x12, 0x78, 0x45, 0xcb, 0x52,
	0x0c, 0x5c, 0x27, 0xd1, 0x6e, 0x91, 0x1e, 0x91, 0x47, 0x88, 0x4e, 0x21, 0xee, 0xff, 0x54, 0xc9,
	0xc2, 0xb2, 0xe6, 0x88, 0xbf, 0xc1, 0xba, 0xc8, 0x67, 0xd5, 0x67, 0xf0, 0x52, 0x32, 0x35, 0xb4,
	0xae, 0x78, 0x43, 0x46, 0x84, 0xde, 0xc1, 0xeb, 0xde, 0xca, 0xae, 0x5d, 0x83, 0x25, 0xf1, 0x18,
	0x7f, 0x81, 0x8d, 0xf7, 0x40, 0x58, 0xdd, 0x28, 0xcd, 0xe4, 0xb3, 0x6c, 0x5c, 0xc0, 0xc6, 0xdb,
	0xf0, 0x0d, 0x0e, 0x38, 0xc1, 0x7f, 0x23, 0x00, 0x27, 0xbd, 0xe6, 0xbf, 0xc4, 0xcc, 0x58, 0x34,
	0x37, 0x86, 0xce, 0x61, 0xe5, 0xce, 0x5f, 0x47, 0x27, 0xee, 0xcd, 0x39, 0x89, 0xde, 0x03, 0x38,
	0xe2, 0x3b, 0xed, 0x58, 0x12, 0xef, 0xa2, 0xf4, 0x88, 0x04, 0xcc, 0x74, 0x9f, 0x8b, 0x86, 0x27,
	0xcb, 0x5d, 0x94, 0x2e, 0x49, 0xc0, 0xe0, 0x0b, 0x58, 0xf9, 0xf1, 0xff, 0x6b, 0x69, 0x13, 0x64,
	0xf5, 0x13, 0x56, 0x7e, 0x54, 0x2b, 0xfe, 0xf0, 0xd8, 0xdd, 0x20, 0x2b, 0x3f, 0xfe, 0xf4, 0x26,
	0xeb, 0x54, 0x9d, 0x4d, 0x22, 0x12, 0x48, 0x82, 0x5c, 0x16, 0xb3, 0x5c, 0xd6, 0x70, 0x92, 0x17,
	0xf7, 0x57, 0x8c, 0x4a, 0xfd, 0xc0, 0xa8, 0xc6, 0x19, 0x9c, 0x14, 0xf9, 0x84, 0xcd, 0x18, 0x8a,
	0xc9, 0xdf, 0x4c, 0xde, 0x35, 0x1d, 0xb3, 0x0f, 0x21, 0x12, 0x30, 0xf8, 0x34, 0xd8, 0x24, 0xc2,
	0x68, 0xb5, 0xc7, 0x69, 0xb0, 0x1d, 0x96, 0x39, 0xf8, 0x9f, 0x9c, 0xc1, 0xd6, 0xd7, 0xe6, 0x94,
	0x97, 0xac, 0x75, 0x1d, 0x32, 0xd8, 0xfa, 0x0e, 0x01, 0x7f, 0xb0, 0xcf, 0x10, 0xa4, 0x93, 0x53,
	0x59, 0x19, 0x61, 0x49, 0x65, 0x65, 0x83, 0x8c, 0x8d, 0xd0, 0xa1, 0xa7, 0xd6, 0xd1, 0xde, 0x09,
	0xd5, 0xe8, 0x46, 0xf0, 0x24, 0x1e, 0xe3, 0x1f, 0x31, 0xda, 0xc2, 0x0b, 0xd3, 0x41, 0x25, 0x4b,
	0x7b, 0xe1, 0x00, 0x7e, 0x1b, 0x2c, 0xf0, 0xa5, 0xa4, 0x0f, 0x57, 0x42, 0x69, 0x43, 0x7a, 0x2f,
	0x9e, 0x3c, 0x07, 0x30, 0xca, 0x41, 0x3f, 0xe5, 0xce, 0xa8, 0x4c, 0xe9, 0xa4, 0xf2, 0xc3, 0x46,
	0xc1, 0xb0, 0x1f, 0xed, 0xb0, 0x97, 0xb4, 0x63, 0xc4, 0x7d, 0x63, 0x3b, 0x38, 0xae, 0x69, 0xc7,
	0x7e, 0x34, 0xfc, 0x6e, 0xdf, 0xb3, 0x31, 0x9a, 0x90, 0xfa, 0x17, 0x00, 0x00, 0xff, 0xff, 0x5b,
	0xaf, 0x87, 0x58, 0x09, 0x04, 0x00, 0x00,
}
