// Code generated by protoc-gen-go. DO NOT EDIT.
// source: LoginInfo.proto

/*
Package PlayerLogin is a generated protocol buffer package.

It is generated from these files:
	LoginInfo.proto

It has these top-level messages:
	CS_PlayerLogin
	SC_PlayerLogin
	CS_PlayerRegister
	SC_PlayerRegister
*/
package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SC_PlayerLogin_LoginResult int32

const (
	SC_PlayerLogin_ACCOUNT_ERROR SC_PlayerLogin_LoginResult = 0
	SC_PlayerLogin_PWD_ERROR     SC_PlayerLogin_LoginResult = 1
)

var SC_PlayerLogin_LoginResult_name = map[int32]string{
	0: "ACCOUNT_ERROR",
	1: "PWD_ERROR",
}
var SC_PlayerLogin_LoginResult_value = map[string]int32{
	"ACCOUNT_ERROR": 0,
	"PWD_ERROR":     1,
}

func (x SC_PlayerLogin_LoginResult) String() string {
	return proto.EnumName(SC_PlayerLogin_LoginResult_name, int32(x))
}
func (SC_PlayerLogin_LoginResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

type SC_PlayerRegister_RegisterResult int32

const (
	SC_PlayerRegister_ACCOUNT_ERROR SC_PlayerRegister_RegisterResult = 0
)

var SC_PlayerRegister_RegisterResult_name = map[int32]string{
	0: "ACCOUNT_ERROR",
}
var SC_PlayerRegister_RegisterResult_value = map[string]int32{
	"ACCOUNT_ERROR": 0,
}

func (x SC_PlayerRegister_RegisterResult) String() string {
	return proto.EnumName(SC_PlayerRegister_RegisterResult_name, int32(x))
}
func (SC_PlayerRegister_RegisterResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3, 0}
}

type CS_PlayerLogin struct {
	Account string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Pwd     string `protobuf:"bytes,2,opt,name=pwd" json:"pwd,omitempty"`
}

func (m *CS_PlayerLogin) Reset()                    { *m = CS_PlayerLogin{} }
func (m *CS_PlayerLogin) String() string            { return proto.CompactTextString(m) }
func (*CS_PlayerLogin) ProtoMessage()               {}
func (*CS_PlayerLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CS_PlayerLogin) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CS_PlayerLogin) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type SC_PlayerLogin struct {
	LoginResult SC_PlayerLogin_LoginResult `protobuf:"varint,1,opt,name=loginResult,enum=PlayerLogin.SC_PlayerLogin_LoginResult" json:"loginResult,omitempty"`
}

func (m *SC_PlayerLogin) Reset()                    { *m = SC_PlayerLogin{} }
func (m *SC_PlayerLogin) String() string            { return proto.CompactTextString(m) }
func (*SC_PlayerLogin) ProtoMessage()               {}
func (*SC_PlayerLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SC_PlayerLogin) GetLoginResult() SC_PlayerLogin_LoginResult {
	if m != nil {
		return m.LoginResult
	}
	return SC_PlayerLogin_ACCOUNT_ERROR
}

type CS_PlayerRegister struct {
	Account string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Pwd     string `protobuf:"bytes,2,opt,name=pwd" json:"pwd,omitempty"`
}

func (m *CS_PlayerRegister) Reset()                    { *m = CS_PlayerRegister{} }
func (m *CS_PlayerRegister) String() string            { return proto.CompactTextString(m) }
func (*CS_PlayerRegister) ProtoMessage()               {}
func (*CS_PlayerRegister) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CS_PlayerRegister) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CS_PlayerRegister) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type SC_PlayerRegister struct {
	RegisterResult SC_PlayerRegister_RegisterResult `protobuf:"varint,1,opt,name=registerResult,enum=PlayerLogin.SC_PlayerRegister_RegisterResult" json:"registerResult,omitempty"`
}

func (m *SC_PlayerRegister) Reset()                    { *m = SC_PlayerRegister{} }
func (m *SC_PlayerRegister) String() string            { return proto.CompactTextString(m) }
func (*SC_PlayerRegister) ProtoMessage()               {}
func (*SC_PlayerRegister) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SC_PlayerRegister) GetRegisterResult() SC_PlayerRegister_RegisterResult {
	if m != nil {
		return m.RegisterResult
	}
	return SC_PlayerRegister_ACCOUNT_ERROR
}

func init() {
	proto.RegisterType((*CS_PlayerLogin)(nil), "PlayerLogin.CS_PlayerLogin")
	proto.RegisterType((*SC_PlayerLogin)(nil), "PlayerLogin.SC_PlayerLogin")
	proto.RegisterType((*CS_PlayerRegister)(nil), "PlayerLogin.CS_PlayerRegister")
	proto.RegisterType((*SC_PlayerRegister)(nil), "PlayerLogin.SC_PlayerRegister")
	proto.RegisterEnum("PlayerLogin.SC_PlayerLogin_LoginResult", SC_PlayerLogin_LoginResult_name, SC_PlayerLogin_LoginResult_value)
	proto.RegisterEnum("PlayerLogin.SC_PlayerRegister_RegisterResult", SC_PlayerRegister_RegisterResult_name, SC_PlayerRegister_RegisterResult_value)
}

func init() { proto.RegisterFile("LoginInfo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xf7, 0xc9, 0x4f, 0xcf,
	0xcc, 0xf3, 0xcc, 0x4b, 0xcb, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x0e, 0xc8, 0x49,
	0xac, 0x4c, 0x2d, 0x02, 0x0b, 0x2b, 0xd9, 0x70, 0xf1, 0x39, 0x07, 0xc7, 0x23, 0x89, 0x08, 0x49,
	0x70, 0xb1, 0x27, 0x26, 0x27, 0xe7, 0x97, 0xe6, 0x95, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06,
	0xc1, 0xb8, 0x42, 0x02, 0x5c, 0xcc, 0x05, 0xe5, 0x29, 0x12, 0x4c, 0x60, 0x51, 0x10, 0x53, 0xa9,
	0x87, 0x91, 0x8b, 0x2f, 0xd8, 0x19, 0x45, 0xbb, 0x27, 0x17, 0x77, 0x0e, 0x88, 0x11, 0x94, 0x5a,
	0x5c, 0x9a, 0x03, 0x31, 0x82, 0xcf, 0x48, 0x5d, 0x0f, 0x49, 0x89, 0x1e, 0xaa, 0x0e, 0x3d, 0x1f,
	0x84, 0xf2, 0x20, 0x64, 0xbd, 0x4a, 0xfa, 0x5c, 0xdc, 0x48, 0x72, 0x42, 0x82, 0x5c, 0xbc, 0x8e,
	0xce, 0xce, 0xfe, 0xa1, 0x7e, 0x21, 0xf1, 0xae, 0x41, 0x41, 0xfe, 0x41, 0x02, 0x0c, 0x42, 0xbc,
	0x5c, 0x9c, 0x01, 0xe1, 0x2e, 0x50, 0x2e, 0xa3, 0x92, 0x3d, 0x97, 0x20, 0xdc, 0x33, 0x41, 0xa9,
	0xe9, 0x99, 0xc5, 0x25, 0xa9, 0x45, 0x24, 0xf9, 0xa7, 0x9f, 0x91, 0x4b, 0x10, 0xee, 0x3a, 0xb8,
	0x09, 0xa1, 0x5c, 0x7c, 0x45, 0x50, 0x36, 0x8a, 0xaf, 0x74, 0xb1, 0xfb, 0x0a, 0xa6, 0x4f, 0x2f,
	0x08, 0x45, 0x53, 0x10, 0x9a, 0x21, 0x4a, 0xca, 0x5c, 0x7c, 0xa8, 0x2a, 0xb0, 0xf8, 0x30, 0x89,
	0x0d, 0x1c, 0x67, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x45, 0x52, 0xf7, 0x87, 0xc6, 0x01,
	0x00, 0x00,
}
