// Code generated by protoc-gen-go. DO NOT EDIT.
// source: WeiQi.proto

/*
Package GameMsg is a generated protocol buffer package.

It is generated from these files:
	WeiQi.proto

It has these top-level messages:
	CS_Login
	SC_Login
*/
package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SC_Login_LoginResult int32

const (
	SC_Login_ACCOUNT_ERROR  SC_Login_LoginResult = 0
	SC_Login_PWD_ERROR      SC_Login_LoginResult = 1
	SC_Login_ACCOUNT_FREEZE SC_Login_LoginResult = 2
)

var SC_Login_LoginResult_name = map[int32]string{
	0: "ACCOUNT_ERROR",
	1: "PWD_ERROR",
	2: "ACCOUNT_FREEZE",
}
var SC_Login_LoginResult_value = map[string]int32{
	"ACCOUNT_ERROR":  0,
	"PWD_ERROR":      1,
	"ACCOUNT_FREEZE": 2,
}

func (x SC_Login_LoginResult) String() string {
	return proto.EnumName(SC_Login_LoginResult_name, int32(x))
}
func (SC_Login_LoginResult) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type CS_Login struct {
	Account string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Pwd     string `protobuf:"bytes,2,opt,name=pwd" json:"pwd,omitempty"`
}

func (m *CS_Login) Reset()                    { *m = CS_Login{} }
func (m *CS_Login) String() string            { return proto.CompactTextString(m) }
func (*CS_Login) ProtoMessage()               {}
func (*CS_Login) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CS_Login) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CS_Login) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type SC_Login struct {
	LoginResult SC_Login_LoginResult `protobuf:"varint,1,opt,name=loginResult,enum=GameMsg.SC_Login_LoginResult" json:"loginResult,omitempty"`
	Account     string               `protobuf:"bytes,2,opt,name=account" json:"account,omitempty"`
}

func (m *SC_Login) Reset()                    { *m = SC_Login{} }
func (m *SC_Login) String() string            { return proto.CompactTextString(m) }
func (*SC_Login) ProtoMessage()               {}
func (*SC_Login) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SC_Login) GetLoginResult() SC_Login_LoginResult {
	if m != nil {
		return m.LoginResult
	}
	return SC_Login_ACCOUNT_ERROR
}

func (m *SC_Login) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func init() {
	proto.RegisterType((*CS_Login)(nil), "GameMsg.CS_Login")
	proto.RegisterType((*SC_Login)(nil), "GameMsg.SC_Login")
	proto.RegisterEnum("GameMsg.SC_Login_LoginResult", SC_Login_LoginResult_name, SC_Login_LoginResult_value)
}

func init() { proto.RegisterFile("WeiQi.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0e, 0x4f, 0xcd, 0x0c,
	0xcc, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x77, 0x4f, 0xcc, 0x4d, 0xf5, 0x2d, 0x4e,
	0x57, 0x32, 0xe3, 0xe2, 0x70, 0x0e, 0x8e, 0xf7, 0xc9, 0x4f, 0xcf, 0xcc, 0x13, 0x92, 0xe0, 0x62,
	0x4f, 0x4c, 0x4e, 0xce, 0x2f, 0xcd, 0x2b, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x71,
	0x85, 0x04, 0xb8, 0x98, 0x0b, 0xca, 0x53, 0x24, 0x98, 0xc0, 0xa2, 0x20, 0xa6, 0xd2, 0x2a, 0x46,
	0x2e, 0x8e, 0x60, 0x67, 0xa8, 0x46, 0x7b, 0x2e, 0xee, 0x1c, 0x10, 0x23, 0x28, 0xb5, 0xb8, 0x34,
	0x07, 0xa2, 0x99, 0xcf, 0x48, 0x56, 0x0f, 0x6a, 0x87, 0x1e, 0x4c, 0x9d, 0x9e, 0x0f, 0x42, 0x51,
	0x10, 0xb2, 0x0e, 0x64, 0x9b, 0x99, 0x50, 0x6c, 0x56, 0x72, 0xe6, 0xe2, 0x46, 0xd2, 0x25, 0x24,
	0xc8, 0xc5, 0xeb, 0xe8, 0xec, 0xec, 0x1f, 0xea, 0x17, 0x12, 0xef, 0x1a, 0x14, 0xe4, 0x1f, 0x24,
	0xc0, 0x20, 0xc4, 0xcb, 0xc5, 0x19, 0x10, 0xee, 0x02, 0xe5, 0x32, 0x0a, 0x09, 0x71, 0xf1, 0xc1,
	0x54, 0xb8, 0x05, 0xb9, 0xba, 0x46, 0xb9, 0x0a, 0x30, 0x25, 0xb1, 0x81, 0x3d, 0x6d, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x8b, 0xa2, 0x4d, 0x28, 0x03, 0x01, 0x00, 0x00,
}
